# Silabs components are readily packaged for debian and requires bookworm deps
FROM debian:bookworm-slim

# Setup installation and DOCKER env
ENV DEBIAN_FRONTEND=noninteractive
ENV DOCKER=1

# Update packages
RUN apt-get update

# Dependencies for setup
RUN apt-get install -y \
    lsb-release \
    wget \
    unzip \
    make

# Download Silabs packages
WORKDIR /tmp/silabs
RUN wget https://github.com/SiliconLabs/simplicity_sdk/releases/latest/download/debian-bookworm.zip
RUN unzip debian-bookworm.zip -d multiprotocol-packages

# Install cpcd and ot-br
RUN ARCH=$(dpkg --print-architecture) && \
    echo "Detected architecture: $ARCH" && \
    apt-get install -y \
    ./multiprotocol-packages/debian-bookworm/deb/libcpc3_*_${ARCH}.deb \
    ./multiprotocol-packages/debian-bookworm/deb/cpcd_*_${ARCH}.deb

# CPCd configuration
COPY ./cpcd.conf /etc/cpcd.conf

# Start from root homedir
WORKDIR /root

# Cleanup
RUN apt-get remove -y \
    lsb-release \
    wget \
    unzip \
    make
RUN apt-get autoremove -y
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /tmp/silabs

CMD ["cpcd"]
